import { sql } from 'drizzle-orm'
import {
  check,
  index,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core'

/**
 * Where a dog can be. An elimination anywhere but `outside` is an accident,
 * which still holds for the crate and the bed. Appended rather than reordered:
 * the existing three keep their place in the deck.
 */
export const location = pgEnum('location', ['pen', 'outside', 'inside', 'crate', 'bed'])

export const eventType = pgEnum('event_type', [
  'location',
  'potty',
  'meal',
  'water',
  'sleep',
])

export const pottyKind = pgEnum('potty_kind', ['pee', 'poo', 'both'])

export const dogs = pgTable('dogs', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  /** Tailwind hue token; the two dogs are told apart by colour everywhere. */
  accent: text('accent').notNull(),
  /** Stands in for the name in the timeline, where rows must stay scannable. */
  emoji: text('emoji').notNull().default('🐶'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

/**
 * One timeline per dog. A single table keeps "what happened today" a single
 * ordered read, which is the only query the UI makes on the hot path. The
 * per-type columns are nullable and the union is enforced by CHECK constraints
 * below, so the database rejects a half-formed event the client never should
 * have sent.
 *
 * `id` is generated by the client, not the database: an offline log queued in
 * the outbox carries its own identity, so replaying the queue is idempotent.
 */
export const events = pgTable(
  'events',
  {
    id: uuid('id').primaryKey(),
    dogId: uuid('dog_id')
      .notNull()
      .references(() => dogs.id, { onDelete: 'cascade' }),
    type: eventType('type').notNull(),
    /** When it happened — set on the device, which may be hours before sync. */
    occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull(),
    /** Sleep only; null while a nap is still in progress. */
    endedAt: timestamp('ended_at', { withTimezone: true }),
    location: location('location'),
    pottyKind: pottyKind('potty_kind'),
    /** Meal in cups, water in ounces. */
    amount: numeric('amount', { precision: 6, scale: 2 }),
    note: text('note'),
    /** Tombstone. Undo must propagate to other devices, so rows are never removed. */
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    /**
     * Bumped on every write, including a tombstone or an edited note. The pull
     * cursor runs on this rather than `created_at`: an update leaves creation
     * time alone, so cursoring on it means a delete made on one device is never
     * delivered to any device that already held the row.
     *
     * Millisecond precision on purpose: the cursor travels as an ISO string,
     * which cannot carry the microseconds Postgres stores by default, so the
     * newest row would compare as greater than its own cursor and be handed
     * back on every single pull.
     */
    updatedAt: timestamp('updated_at', { withTimezone: true, precision: 3 })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index('events_dog_occurred_idx').on(t.dogId, t.occurredAt.desc()),
    /** The sync pull is "everything the server changed after my cursor". */
    index('events_updated_idx').on(t.updatedAt),
    check(
      'location_event_has_place',
      sql`${t.type} <> 'location' or ${t.location} is not null`,
    ),
    check(
      'potty_event_is_complete',
      sql`${t.type} <> 'potty' or (${t.location} is not null and ${t.pottyKind} is not null)`,
    ),
    check(
      'intake_event_has_amount',
      sql`${t.type} not in ('meal', 'water') or ${t.amount} is not null`,
    ),
    check(
      'sleep_ends_after_it_starts',
      sql`${t.endedAt} is null or ${t.endedAt} >= ${t.occurredAt}`,
    ),
  ],
)

export type Dog = typeof dogs.$inferSelect
export type Event = typeof events.$inferSelect
export type NewEvent = typeof events.$inferInsert
