import { sql } from 'drizzle-orm'
import {
  boolean,
  check,
  index,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core'

/**
 * Where a dog can be. An elimination anywhere but `outside` is an accident,
 * which still holds for the crate and the bed. Appended rather than reordered:
 * the existing three keep their place in the deck.
 */
export const location = pgEnum('location', ['pen', 'outside', 'inside', 'crate', 'bed'])

export const eventType = pgEnum('event_type', [
  'location',
  'potty',
  'bark',
  'meal',
  'water',
  'sleep',
])

export const pottyKind = pgEnum('potty_kind', ['pee', 'poo', 'both'])

/**
 * Better Auth's tables, with its own default names and columns. `users` is its
 * `user` model, mapped by name in `src/server/auth.ts`.
 *
 * Text ids rather than the uuid the rest of this schema uses: Better Auth mints
 * them, and `advanced.database.generateId` is set to crypto.randomUUID so the
 * values are uuids even though the column is not.
 */
export const users = pgTable('users', {
  id: text('id').primaryKey(),
  email: text('email').notNull().unique(),
  name: text('name'),
  image: text('image'),
  /** Required by Better Auth. Sign-in does not wait on it. */
  emailVerified: boolean('email_verified').notNull().default(false),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
})

export const session = pgTable('session', {
  id: text('id').primaryKey(),
  userId: text('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  token: text('token').notNull().unique(),
  expiresAt: timestamp('expires_at', { withTimezone: true, mode: 'date' }).notNull(),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
})

/** One authentication method per row. Email and password is `providerId: 'credential'`. */
export const account = pgTable('account', {
  id: text('id').primaryKey(),
  userId: text('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  accountId: text('account_id').notNull(),
  providerId: text('provider_id').notNull(),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  idToken: text('id_token'),
  accessTokenExpiresAt: timestamp('access_token_expires_at', { withTimezone: true, mode: 'date' }),
  refreshTokenExpiresAt: timestamp('refresh_token_expires_at', { withTimezone: true, mode: 'date' }),
  scope: text('scope'),
  password: text('password'),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
})

/** Short-lived tokens: email verification and password reset. */
export const verification = pgTable('verification', {
  id: text('id').primaryKey(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true, mode: 'date' }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
})

export const dogs = pgTable('dogs', {
  id: uuid('id').primaryKey().defaultRandom(),
  /**
   * Nullable only so the rows that predate accounts could be adopted rather than
   * dropped. Everything written since belongs to somebody; see
   * `scripts/claim-dogs.ts`.
   */
  userId: text('user_id').references(() => users.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  /** Tailwind hue token; the two dogs are told apart by colour everywhere. */
  accent: text('accent').notNull(),
  /** Stands in for the name in the timeline, where rows must stay scannable. */
  emoji: text('emoji').notNull().default('🐶'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

/**
 * One timeline per dog. A single table keeps "what happened today" a single
 * ordered read, which is the only query the UI makes on the hot path. The
 * per-type columns are nullable and the union is enforced by CHECK constraints
 * below, so the database rejects a half-formed event the client never should
 * have sent.
 *
 * `id` is generated by the client, not the database: an offline log queued in
 * the outbox carries its own identity, so replaying the queue is idempotent.
 */
export const events = pgTable(
  'events',
  {
    id: uuid('id').primaryKey(),
    dogId: uuid('dog_id')
      .notNull()
      .references(() => dogs.id, { onDelete: 'cascade' }),
    type: eventType('type').notNull(),
    /** When it happened — set on the device, which may be hours before sync. */
    occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull(),
    location: location('location'),
    pottyKind: pottyKind('potty_kind'),
    /** Meal in cups, water in ounces. */
    amount: numeric('amount', { precision: 6, scale: 2 }),
    note: text('note'),
    /** Tombstone. Undo must propagate to other devices, so rows are never removed. */
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    /**
     * Bumped on every write, including a tombstone or an edited note. The pull
     * cursor runs on this rather than `created_at`: an update leaves creation
     * time alone, so cursoring on it means a delete made on one device is never
     * delivered to any device that already held the row.
     *
     * Millisecond precision on purpose: the cursor travels as an ISO string,
     * which cannot carry the microseconds Postgres stores by default, so the
     * newest row would compare as greater than its own cursor and be handed
     * back on every single pull.
     */
    updatedAt: timestamp('updated_at', { withTimezone: true, precision: 3 })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index('events_dog_occurred_idx').on(t.dogId, t.occurredAt.desc()),
    /** The sync pull is "everything the server changed after my cursor". */
    index('events_updated_idx').on(t.updatedAt),
    check(
      'location_event_has_place',
      sql`${t.type} <> 'location' or ${t.location} is not null`,
    ),
    check(
      'potty_event_is_complete',
      sql`${t.type} <> 'potty' or (${t.location} is not null and ${t.pottyKind} is not null)`,
    ),
    check('bark_event_has_place', sql`${t.type} <> 'bark' or ${t.location} is not null`),
    check(
      'meal_event_has_place',
      sql`${t.type} <> 'meal' or ${t.location} is not null`,
    ),
    check(
      'water_event_has_amount',
      sql`${t.type} <> 'water' or ${t.amount} is not null`,
    ),
    check(
      'sleep_event_has_place',
      sql`${t.type} <> 'sleep' or ${t.location} is not null`,
    ),
  ],
)

export type User = typeof users.$inferSelect
export type Dog = typeof dogs.$inferSelect
export type Event = typeof events.$inferSelect
export type NewEvent = typeof events.$inferInsert
